### ISSUE TITLE
Warning: incorrect peer dependency

### ISSUE THREAD

**Issue by sergejmueller** [webpack-contrib/stylelint-webpack-plugin#166] opened 2018-08-24 09:53 UTC
* Operating System: Mac OS
* Node Version: 8.9.0
* NPM Version: 5.5.1
* webpack Version: 4.16.5
* stylelint-webpack-plugin Version: 0.10.5

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

```bash
  # paste the CLI command you're using. if this isn't applicable, it's safe to remove.
  $ yarn
```

### Expected Behavior

No warnings

### Actual Behavior

```bash
warning " > stylelint-webpack-plugin@0.10.5" has incorrect peer dependency "stylelint@^8.0.0".
```

### How Do We Reproduce?
```bash
yarn
```

**Comment by brlodi** [comment] 2018-08-24 22:06
You need to explicitly install `stylelint` with a range of `^8.0.0`, so anything `8.x.x`. That's not a bug, that's just how peer dependencies work.

If you mean to request that the peer dependency be changed to include Stylelint v9.x, that's a duplicate of #149.

**Closed** 2019-08-07 17:07 UTC
